apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chatapp
type: Opaque
stringData:
  JWT_SECRET: "change-me-super-secret-jwt-key-at-least-32-chars"
  JWT_REFRESH_SECRET: "change-me-super-secret-refresh-key-32chars"
  INTERNAL_API_TOKEN: "change-me-internal-api-token-32chars!!"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://root:password@mongodb:27017/chatapp?authSource=admin"
  AUTH_DB_URL: "postgresql://chatapp_auth:chatapp_password@postgresql-auth:5432/chatapp_auth"
  USER_DB_URL: "postgresql://chatapp_user:chatapp_password@postgresql-user:5432/chatapp_user"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
