input {
  tcp {
    port => 5044
    codec => json_lines
  }
  udp {
    port => 5001
    codec => json_lines
  }
}

filter {
  if [service] {
    mutate {
      add_field => { "[@metadata][index_prefix]" => "chatapp-%{[service]}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][index_prefix]" => "chatapp-logs" }
    }
  }

  date {
    match => ["time", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][index_prefix]}-%{+YYYY.MM.dd}"
  }
}
