replicaCount: 2
image:
  repository: chatapp-chat-service
  tag: latest
service:
  type: ClusterIP
  port: 4002
  targetPort: 4002
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 500m
    memory: 512Mi
